name: PlayerStats
version: '${version}'
main: org.dasultra.main.Main
api-version: '1.20'
authors: [DasUltra]
description: PlayerStats
website: https://team-ultra.eu

commands:
  stats:
    description: PlayerStats